import Head from "next/head";
import afeaApi from "../api-methods/AfeaApi";
import BlogList from "../components/blog-list/blog-list";
import styles from "../styles/Home.module.css";

export default function Home({blogs}) {
  console.log(blogs)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {blogs && blogs.posts && blogs.posts.length!==0 &&(
        <BlogList blogs={blogs.posts}/>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const blogs= await afeaApi.getAllBlogs(10,0,'id','asc');
  return {
    props:{
      blogs:blogs
    },
    revalidate:100
  }

}